In [18]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [121]:
df = pd.read_csv('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

# 🍟 Pandas version

What version of Pandas did you install?

In [19]:
pd.__version__

'3.0.6'

# 🍟 Records count

How many records are in the dataset?

In [14]:
df.shape[0]

10000

# 🍟 Fuel types

How many fuel types are presented in the dataset?

In [98]:
df['fuel_type'].value_counts()

fuel_type
Gasoline    6913
Diesel      2053
Hybrid      1034
Name: count, dtype: int64

# 🍟 Missing values

How many columns in the dataset have missing values?

In [24]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

# 🍟 Max fuel efficiency

What's the maximum fuel efficiency of cars from Asia?

In [99]:
df[df['origin']=='Asia']['fuel_efficiency_mpg'].max()

np.float64(41.2)

# 🍟 Median value of horsepower

1. Find the median value of the horsepower column in the dataset.
2. Next, calculate the most frequent value of the same horsepower column.
3. Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.
4. Now, calculate the median value of horsepower once again.

Has it changed?

In [113]:
# Find the median value of the horsepower column in the dataset.

median_value = df['horsepower'].median()
median_value

np.float64(254.0)

In [114]:
# Next, calculate the most frequent value of the same horsepower column.

mode_value = df['horsepower'].mode()[0]
mode_value

np.float64(252.0)

In [115]:
# Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.

df['horsepower'].isnull().value_counts()

horsepower
False    9123
True      877
Name: count, dtype: int64

In [116]:
new_df = df['horsepower'].fillna(mode_value)

In [117]:
new_df.isnull().value_counts()

horsepower
False    10000
Name: count, dtype: int64

In [119]:
new_df

0       243.0
1       272.0
2       267.0
3       258.0
4       304.0
        ...
9995    271.0
9996    244.0
9997    267.0
9998    270.0
9999    295.0
Name: horsepower, Length: 10000, dtype: float64

In [120]:
# Now, calculate the median value of horsepower once again.

new_median_value = new_df.median()
new_median_value

np.float64(252.0)

# 🍟 Sum of weights

1. Select all the cars from Asia
2. Select only columns vehicle_weight and model_year
3. Select the first 7 values
4. Get the underlying NumPy array. Let's call it X.
5. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
6. Invert XTX.
7. Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
8. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
9. What's the sum of all the elements of the result?

>Note: You just implemented linear regression. We'll talk about it in the next lesson.

In [87]:
# Select all the cars from Asia

df_Asia = df[df['origin']=='Asia']
df_Asia.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,NaN,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4

In [88]:
# Select only columns vehicle_weight and model_year

df_2_columns = df_Asia[['vehicle_weight', 'model_year']]
df_2_columns.head()

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007

In [89]:
# Select the first 7 values

df_first_7_values = df_2_columns[:7]
df_first_7_values

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [90]:
# Get the underlying NumPy array. Let's call it X

X = df_first_7_values.to_numpy()
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [93]:
# Compute matrix-matrix multiplication between the transpose of X and X. 
# To get the transpose, use X.T. Let's call the result XTX.

XTX = X.T.dot(X)
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [94]:
# Invert XTX

XTX_inverse = np.linalg.inv(XTX)
XTX_inverse

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [77]:
# Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].

y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [79]:
# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w

new_values = XTX_inverse.dot(X.T)
w = new_values.dot(y)
w

array([0.13644777, 0.2327492 ])

In [100]:
# What's the sum of all the elements of the result?

w.sum()

np.float64(0.36919696904925486)